title: Andraine Wallace # your name (or website title) here
logo: "/images/user_img.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Enthusiastic and data-driven professional showcasing skills in data analysis and problem solving that improves business processes and increase profits. 
  <br><br>
  
  <a href="https://www.linkedin.com/in/andrainew/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
