title: Andraine Wallace # your name (or website title) here
logo: "/images/fpmg.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data-driven professional experienced in project management, data analytics, and business intelligence. Demonstrated analytical abilities in data acquisition, cleaning, mining, revenue forecasting, predictive modeling, and sentiment analysis using machine learning algorithms. Strong problem-solving and communication skills, with a passion for using data to drive business decisions. Technical skills and tools include SQL, Python, Machine Learning, Project Management, Microsoft Office, Tableau, Jupyter Lab, Google Colab, and GitHub.
  <br><br>
  <a href="https://www.linkedin.com/in/andrainew/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
